#!/bin/bash - 
#======================================================
#
#          FILE: validation.sh
# 
USAGE="./validation.sh"
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: --- unknown
#         NOTES: ---
#        AUTHOR: |CHAO.TANG| , |chao.tang.1@gmail.com|
#  ORGANIZATION: 
#       CREATED: 04/03/17 22:37
#      REVISION: 1.0
#=====================================================
set -o nounset           # Treat unset variables as an error
. ~/Shell/functions.sh   # ctang's functions

DIR=/Users/ctang/climate/GLOBALDATA/OBSDATA/CM_SAF/SIS/CDR_v001
file=SISmm.CDR.mon.mean.198301-200512.nc
PWD=$(pwd)
GEBA=GEBA.station.gt.1mon.SA      # 44 stations, generated by mon.flg.SA.8305.py
                                  # where, input all 110 stations output 
                                  # the one with atleast ONE good point
FLAG=GEBA.flag.rsds.monthly.1983-2005.csv  # 110 station
RSDS=GEBA.rsds.monthly.1983-2005.csv       # 110 station

#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  untar
#   DESCRIPTION:  untar CDR data
#    PARAMETERS:  
#       RETURNS:  after untar the tat.gz file will be delete
#-------------------------------------------------------------------------------
function untar()
{
   #cdo splityear $file year
    for year in $(seq -s " " 1983 2005)
    do
        echo $year
        cdo splitmon year$year.nc $year
    done
}


#untar



#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  getstation
#   DESCRIPTION:  sel grid points
#    PARAMETERS:  
#       RETURNS:  $GEBA
#-------------------------------------------------------------------------------
function getstation()
{
    Tline=$(wc -l $GEBA | awk '{print $1}')
    for i in $(seq -s " " 1 $Tline)
    #for i in $(seq -s " " 1 2)
    do
        echo $i
        lat=$(awk 'NR=='$i'{print $3}' $GEBA )
        lon=$(awk 'NR=='$i'{print $4}' $GEBA )

	    sta=$(awk 'NR=='$i'{print $2}' $GEBA)

	    lat1=$(awk 'NR=='$i'{print $3-0.015}' $GEBA)
	    lat2=$(awk 'NR=='$i'{print $3+0.015}' $GEBA)

	    lon1=$(awk 'NR=='$i'{print $4-0.015}' $GEBA)
	    lon2=$(awk 'NR=='$i'{print $4+0.015}' $GEBA)

	    cdo -s sellonlatbox,$lon1,$lon2,$lat1,$lat2 199901.nc test.nc 2>&1-

        nx=$(cdo -s sinfo test.nc | grep lonlat | awk '{print $6}' )

        echo ----- $i --station=$sta, test: box: $lon1,$lon2,$lat1,$lat1,lonlat=$nx

#=================================================== 
        for y in $(seq -s " " 1983 2005)
        do
            for m in 01 02 03 04 05 06 07 08 09 10 11 12
            do
                
                cdo -s sellonlatbox,$lon1,$lon2,$lat1,$lat2 $y$m.nc $y${m}_$sta.nc 2>&1-

                echo $y${m}_$sta.nc $i
            done
        done
    done

}

#getstation

#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  GEBAprepare
#   DESCRIPTION:  get 44 station from all 110 station,GEBA.station.gt.1mon.SA     
#                 generated by mon.flg.SA.8305.py
#    PARAMETERS:  
#       RETURNS: 110*23 years = 2530 record are all considered, select sta with at least 1 mon
#-------------------------------------------------------------------------------

function GEBAprepare()
{
    rm FLAG.mon.GEBA RSDS.mon.GEBA
    for station in $(awk '{print $2}' $GEBA)
    do
        echo $station
        awk -F "," -v val=$station '$1 == val' $FLAG >> FLAG.mon.GEBA
        awk -F "," -v val=$station '$1 == val' $RSDS >> RSDS.mon.GEBA
    done

    # remove all zero year:

    awk -F "," '{sum=0;for(i=4;i<=16;i++) sum+=$i; if(sum>0) print $0","NR}' FLAG.mon.GEBA > flag.mon.GEBA.csv

    # get the same line as flag file for rsds
    rm rsds.mon.GEBA.csv
    for i in $(seq -s " " 1 423)
    do
        n=$(awk -F "," 'NR=='$i'{print $18}' flag.mon.GEBA.csv)

        awk -F "," 'NR=='$n'{print $0","NR}' RSDS.mon.GEBA >> rsds.mon.GEBA.csv

    done
}

#GEBAprepare

#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  CMSprepare
#   DESCRIPTION:  get 44 station from all 110 station, from flag.mon.GEBA.csv
#    PARAMETERS:  
#       RETURNS:  cmsaf.rsds.csv
#-------------------------------------------------------------------------------

function CMSprepare()
{
    output=cmsaf.rsds.csv
    cd MONTH
    echo "#ID,StaID,year,Jan,Feb,Mar,Api,May,Jun,July,Aug,Sep,Oct,Nov,Dec" > $output

    for i in $(seq -s " " 1 423)
    do
        sta=$(awk -F "," 'NR=='$i'{print $1}' ../flag.mon.GEBA.csv)
        ID=$(awk -F "," 'NR=='$i'{print $18}' ../flag.mon.GEBA.csv)
        year=$(awk -F "," 'NR=='$i'{print $3}' ../flag.mon.GEBA.csv)

        echo -n $ID,$sta,$year, >> $output
        for m in 01 02 03 04 05 06 07 08 09 10 11 12
        do
            value=$(getvalue_netCDF.py SIS $year${m}_$sta.nc)
            echo -n $value, >> $output
            echo $ID,$year${m}_$sta.nc
        done
        echo "" >> $output
    done
    cd ../
}

CMSprepare

rm -rf RSDS.mon.GEBA FLAG.mon.GEBA
